/*
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import mde.iot.ucm4iot.ide.contentassist.antlr.internal.InternalUcm4iotParser;
import mde.iot.ucm4iot.services.Ucm4iotGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class Ucm4iotParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(Ucm4iotGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, Ucm4iotGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getIoTUseCaseModelAccess().getAlternatives_0_4(), "rule__IoTUseCaseModel__Alternatives_0_4");
			builder.put(grammarAccess.getUseCaseAccess().getAlternatives_0(), "rule__UseCase__Alternatives_0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getAlternatives_3_6_2(), "rule__ExceptionalUseCase__Alternatives_3_6_2");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getAlternatives_3_6_2_0(), "rule__ExceptionalUseCase__Alternatives_3_6_2_0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getAlternatives_3_7_2(), "rule__ExceptionalUseCase__Alternatives_3_7_2");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getAlternatives_3_7_2_0(), "rule__ExceptionalUseCase__Alternatives_3_7_2_0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getAlternatives_3_8_2(), "rule__ExceptionalUseCase__Alternatives_3_8_2");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getAlternatives_3_8_2_0(), "rule__ExceptionalUseCase__Alternatives_3_8_2_0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getAlternatives_3_6_2(), "rule__HandlerUseCase__Alternatives_3_6_2");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getAlternatives_3_6_2_0(), "rule__HandlerUseCase__Alternatives_3_6_2_0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getAlternatives_3_7_2(), "rule__HandlerUseCase__Alternatives_3_7_2");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getAlternatives_3_7_2_0(), "rule__HandlerUseCase__Alternatives_3_7_2_0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getAlternatives_3_8_2(), "rule__HandlerUseCase__Alternatives_3_8_2");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getAlternatives_3_8_2_0(), "rule__HandlerUseCase__Alternatives_3_8_2_0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getAlternatives_3_9_2(), "rule__HandlerUseCase__Alternatives_3_9_2");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getAlternatives_3_9_2_0(), "rule__HandlerUseCase__Alternatives_3_9_2_0");
			builder.put(grammarAccess.getExtensionBlockAccess().getAlternatives(), "rule__ExtensionBlock__Alternatives");
			builder.put(grammarAccess.getAlternateBlockAccess().getAlternatives_2(), "rule__AlternateBlock__Alternatives_2");
			builder.put(grammarAccess.getAlternateBlockAccess().getAlternatives_5(), "rule__AlternateBlock__Alternatives_5");
			builder.put(grammarAccess.getExceptionalBlockAccess().getAlternatives_2(), "rule__ExceptionalBlock__Alternatives_2");
			builder.put(grammarAccess.getExceptionalBlockAccess().getAlternatives_5(), "rule__ExceptionalBlock__Alternatives_5");
			builder.put(grammarAccess.getOutcomeAccess().getAlternatives(), "rule__Outcome__Alternatives");
			builder.put(grammarAccess.getStepAccess().getAlternatives(), "rule__Step__Alternatives");
			builder.put(grammarAccess.getInteractionStepAccess().getAlternatives_3(), "rule__InteractionStep__Alternatives_3");
			builder.put(grammarAccess.getInvocationStepAccess().getAlternatives_5(), "rule__InvocationStep__Alternatives_5");
			builder.put(grammarAccess.getConditionControlStepAccess().getAlternatives(), "rule__ConditionControlStep__Alternatives");
			builder.put(grammarAccess.getStepNumberAccess().getAlternatives(), "rule__StepNumber__Alternatives");
			builder.put(grammarAccess.getExtensionStepNumberAccess().getAlternatives_0(), "rule__ExtensionStepNumber__Alternatives_0");
			builder.put(grammarAccess.getExceptionAccess().getAlternatives(), "rule__Exception__Alternatives");
			builder.put(grammarAccess.getActorAccess().getAlternatives(), "rule__Actor__Alternatives");
			builder.put(grammarAccess.getPrimaryActorAccess().getAlternatives(), "rule__PrimaryActor__Alternatives");
			builder.put(grammarAccess.getSecondaryActorAccess().getAlternatives(), "rule__SecondaryActor__Alternatives");
			builder.put(grammarAccess.getDeviceActorAccess().getAlternatives_0(), "rule__DeviceActor__Alternatives_0");
			builder.put(grammarAccess.getKeywordStandardModeAccess().getAlternatives_0(), "rule__KeywordStandardMode__Alternatives_0");
			builder.put(grammarAccess.getKeywordStandardModeAccess().getAlternatives_1(), "rule__KeywordStandardMode__Alternatives_1");
			builder.put(grammarAccess.getKeywordExceptionalUseCaseAccess().getAlternatives_0(), "rule__KeywordExceptionalUseCase__Alternatives_0");
			builder.put(grammarAccess.getKeywordExceptionalUseCaseAccess().getAlternatives_1(), "rule__KeywordExceptionalUseCase__Alternatives_1");
			builder.put(grammarAccess.getKeywordHandlerUseCaseAccess().getAlternatives_0(), "rule__KeywordHandlerUseCase__Alternatives_0");
			builder.put(grammarAccess.getKeywordHandlerUseCaseAccess().getAlternatives_1(), "rule__KeywordHandlerUseCase__Alternatives_1");
			builder.put(grammarAccess.getKeywordHandlerUseCaseAccess().getAlternatives_2(), "rule__KeywordHandlerUseCase__Alternatives_2");
			builder.put(grammarAccess.getKeywordScopeAccess().getAlternatives(), "rule__KeywordScope__Alternatives");
			builder.put(grammarAccess.getKeywordIntentionAccess().getAlternatives(), "rule__KeywordIntention__Alternatives");
			builder.put(grammarAccess.getKeywordLevelAccess().getAlternatives(), "rule__KeywordLevel__Alternatives");
			builder.put(grammarAccess.getKeywordMultiplicityAccess().getAlternatives(), "rule__KeywordMultiplicity__Alternatives");
			builder.put(grammarAccess.getKeywordPreconditionAccess().getAlternatives(), "rule__KeywordPrecondition__Alternatives");
			builder.put(grammarAccess.getKeywordPostconditionAccess().getAlternatives(), "rule__KeywordPostcondition__Alternatives");
			builder.put(grammarAccess.getKeywordHandlerClassAccess().getAlternatives_0(), "rule__KeywordHandlerClass__Alternatives_0");
			builder.put(grammarAccess.getKeywordHandlerClassAccess().getAlternatives_1(), "rule__KeywordHandlerClass__Alternatives_1");
			builder.put(grammarAccess.getKeywordContextExceptionAccess().getAlternatives_0(), "rule__KeywordContextException__Alternatives_0");
			builder.put(grammarAccess.getKeywordContextExceptionAccess().getAlternatives_1(), "rule__KeywordContextException__Alternatives_1");
			builder.put(grammarAccess.getKeywordContextExceptionAccess().getAlternatives_2(), "rule__KeywordContextException__Alternatives_2");
			builder.put(grammarAccess.getKeywordMainSuccessScenarioAccess().getAlternatives_0(), "rule__KeywordMainSuccessScenario__Alternatives_0");
			builder.put(grammarAccess.getKeywordMainSuccessScenarioAccess().getAlternatives_1(), "rule__KeywordMainSuccessScenario__Alternatives_1");
			builder.put(grammarAccess.getKeywordMainSuccessScenarioAccess().getAlternatives_2(), "rule__KeywordMainSuccessScenario__Alternatives_2");
			builder.put(grammarAccess.getKeywordExtensionsAccess().getAlternatives(), "rule__KeywordExtensions__Alternatives");
			builder.put(grammarAccess.getKeywordAlternateBlockAccess().getAlternatives(), "rule__KeywordAlternateBlock__Alternatives");
			builder.put(grammarAccess.getKeywordExceptionalBlockAccess().getAlternatives(), "rule__KeywordExceptionalBlock__Alternatives");
			builder.put(grammarAccess.getKeywordStepExceptionalBlockAccess().getAlternatives_0(), "rule__KeywordStepExceptionalBlock__Alternatives_0");
			builder.put(grammarAccess.getKeywordStepExceptionalBlockAccess().getAlternatives_2(), "rule__KeywordStepExceptionalBlock__Alternatives_2");
			builder.put(grammarAccess.getKeywordStepExceptionalBlockAccess().getAlternatives_3(), "rule__KeywordStepExceptionalBlock__Alternatives_3");
			builder.put(grammarAccess.getKeywordSceneExceptionBlockAccess().getAlternatives_0(), "rule__KeywordSceneExceptionBlock__Alternatives_0");
			builder.put(grammarAccess.getKeywordSceneExceptionBlockAccess().getAlternatives_2(), "rule__KeywordSceneExceptionBlock__Alternatives_2");
			builder.put(grammarAccess.getKeywordSceneExceptionBlockAccess().getAlternatives_3(), "rule__KeywordSceneExceptionBlock__Alternatives_3");
			builder.put(grammarAccess.getKeywordChildListBeginsAccess().getAlternatives_0(), "rule__KeywordChildListBegins__Alternatives_0");
			builder.put(grammarAccess.getKeywordChildListBeginsAccess().getAlternatives_1(), "rule__KeywordChildListBegins__Alternatives_1");
			builder.put(grammarAccess.getKeywordChildListBeginsAccess().getAlternatives_2(), "rule__KeywordChildListBegins__Alternatives_2");
			builder.put(grammarAccess.getKeywordChildListEndsAccess().getAlternatives_0(), "rule__KeywordChildListEnds__Alternatives_0");
			builder.put(grammarAccess.getKeywordChildListEndsAccess().getAlternatives_1(), "rule__KeywordChildListEnds__Alternatives_1");
			builder.put(grammarAccess.getKeywordChildListEndsAccess().getAlternatives_2(), "rule__KeywordChildListEnds__Alternatives_2");
			builder.put(grammarAccess.getKeywordPrimaryActorAccess().getAlternatives_0(), "rule__KeywordPrimaryActor__Alternatives_0");
			builder.put(grammarAccess.getKeywordPrimaryActorAccess().getAlternatives_1(), "rule__KeywordPrimaryActor__Alternatives_1");
			builder.put(grammarAccess.getKeywordSecondaryActorAccess().getAlternatives_0(), "rule__KeywordSecondaryActor__Alternatives_0");
			builder.put(grammarAccess.getKeywordSecondaryActorAccess().getAlternatives_1(), "rule__KeywordSecondaryActor__Alternatives_1");
			builder.put(grammarAccess.getKeywordFacilitatorActorAccess().getAlternatives_0(), "rule__KeywordFacilitatorActor__Alternatives_0");
			builder.put(grammarAccess.getKeywordFacilitatorActorAccess().getAlternatives_1(), "rule__KeywordFacilitatorActor__Alternatives_1");
			builder.put(grammarAccess.getKeywordExceptionAccess().getAlternatives(), "rule__KeywordException__Alternatives");
			builder.put(grammarAccess.getKeywordOutcomeEndsAccess().getAlternatives_0(), "rule__KeywordOutcomeEnds__Alternatives_0");
			builder.put(grammarAccess.getKeywordOutcomeEndsAccess().getAlternatives_1(), "rule__KeywordOutcomeEnds__Alternatives_1");
			builder.put(grammarAccess.getKeywordOutcomeEndsAccess().getAlternatives_2(), "rule__KeywordOutcomeEnds__Alternatives_2");
			builder.put(grammarAccess.getKeywordOutcomeEndsAccess().getAlternatives_3(), "rule__KeywordOutcomeEnds__Alternatives_3");
			builder.put(grammarAccess.getKeywordOutcomeContAccess().getAlternatives_0(), "rule__KeywordOutcomeCont__Alternatives_0");
			builder.put(grammarAccess.getKeywordOutcomeContAccess().getAlternatives_1(), "rule__KeywordOutcomeCont__Alternatives_1");
			builder.put(grammarAccess.getKeywordOutcomeContAccess().getAlternatives_2(), "rule__KeywordOutcomeCont__Alternatives_2");
			builder.put(grammarAccess.getKeywordOutcomeContAccess().getAlternatives_3(), "rule__KeywordOutcomeCont__Alternatives_3");
			builder.put(grammarAccess.getKeywordOutcomeContAccess().getAlternatives_4(), "rule__KeywordOutcomeCont__Alternatives_4");
			builder.put(grammarAccess.getNoneAccess().getAlternatives(), "rule__None__Alternatives");
			builder.put(grammarAccess.getNotApplicableAccess().getAlternatives(), "rule__NotApplicable__Alternatives");
			builder.put(grammarAccess.getLevelAccess().getAlternatives(), "rule__Level__Alternatives");
			builder.put(grammarAccess.getOutcomeEndingsAccess().getAlternatives(), "rule__OutcomeEndings__Alternatives");
			builder.put(grammarAccess.getIoTUseCaseModelAccess().getGroup(), "rule__IoTUseCaseModel__Group__0");
			builder.put(grammarAccess.getIoTUseCaseModelAccess().getGroup_0(), "rule__IoTUseCaseModel__Group_0__0");
			builder.put(grammarAccess.getUseCaseAccess().getGroup(), "rule__UseCase__Group__0");
			builder.put(grammarAccess.getUseCaseAccess().getGroup_4(), "rule__UseCase__Group_4__0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getGroup(), "rule__ExceptionalUseCase__Group__0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getGroup_3_0(), "rule__ExceptionalUseCase__Group_3_0__0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getGroup_3_1(), "rule__ExceptionalUseCase__Group_3_1__0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getGroup_3_2(), "rule__ExceptionalUseCase__Group_3_2__0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getGroup_3_3(), "rule__ExceptionalUseCase__Group_3_3__0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getGroup_3_4(), "rule__ExceptionalUseCase__Group_3_4__0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getGroup_3_5(), "rule__ExceptionalUseCase__Group_3_5__0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getGroup_3_6(), "rule__ExceptionalUseCase__Group_3_6__0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getGroup_3_7(), "rule__ExceptionalUseCase__Group_3_7__0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getGroup_3_7_2_1(), "rule__ExceptionalUseCase__Group_3_7_2_1__0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getGroup_3_7_2_1_1(), "rule__ExceptionalUseCase__Group_3_7_2_1_1__0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getGroup_3_8(), "rule__ExceptionalUseCase__Group_3_8__0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getGroup_3_8_2_1(), "rule__ExceptionalUseCase__Group_3_8_2_1__0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getGroup_3_8_2_1_1(), "rule__ExceptionalUseCase__Group_3_8_2_1_1__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup(), "rule__HandlerUseCase__Group__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_0(), "rule__HandlerUseCase__Group_3_0__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_1(), "rule__HandlerUseCase__Group_3_1__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_2(), "rule__HandlerUseCase__Group_3_2__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_3(), "rule__HandlerUseCase__Group_3_3__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_4(), "rule__HandlerUseCase__Group_3_4__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_5(), "rule__HandlerUseCase__Group_3_5__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_6(), "rule__HandlerUseCase__Group_3_6__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_7(), "rule__HandlerUseCase__Group_3_7__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_7_2_1(), "rule__HandlerUseCase__Group_3_7_2_1__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_7_2_1_1(), "rule__HandlerUseCase__Group_3_7_2_1_1__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_8(), "rule__HandlerUseCase__Group_3_8__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_8_2_1(), "rule__HandlerUseCase__Group_3_8_2_1__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_8_2_1_1(), "rule__HandlerUseCase__Group_3_8_2_1_1__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_9(), "rule__HandlerUseCase__Group_3_9__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_10(), "rule__HandlerUseCase__Group_3_10__0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getGroup_3_10_3(), "rule__HandlerUseCase__Group_3_10_3__0");
			builder.put(grammarAccess.getMainScenarioAccess().getGroup(), "rule__MainScenario__Group__0");
			builder.put(grammarAccess.getAlternateBlockAccess().getGroup(), "rule__AlternateBlock__Group__0");
			builder.put(grammarAccess.getAlternateBlockAccess().getGroup_2_1(), "rule__AlternateBlock__Group_2_1__0");
			builder.put(grammarAccess.getAlternateBlockAccess().getGroup_5_1(), "rule__AlternateBlock__Group_5_1__0");
			builder.put(grammarAccess.getExceptionalBlockAccess().getGroup(), "rule__ExceptionalBlock__Group__0");
			builder.put(grammarAccess.getExceptionalBlockAccess().getGroup_2_1(), "rule__ExceptionalBlock__Group_2_1__0");
			builder.put(grammarAccess.getExceptionalBlockAccess().getGroup_5_1(), "rule__ExceptionalBlock__Group_5_1__0");
			builder.put(grammarAccess.getOutcomeEndsAccess().getGroup(), "rule__OutcomeEnds__Group__0");
			builder.put(grammarAccess.getOutcomeContinuesAccess().getGroup(), "rule__OutcomeContinues__Group__0");
			builder.put(grammarAccess.getInteractionStepAccess().getGroup(), "rule__InteractionStep__Group__0");
			builder.put(grammarAccess.getInvocationStepAccess().getGroup(), "rule__InvocationStep__Group__0");
			builder.put(grammarAccess.getGroupedStepsAccess().getGroup(), "rule__GroupedSteps__Group__0");
			builder.put(grammarAccess.getMainStepNumberAccess().getGroup(), "rule__MainStepNumber__Group__0");
			builder.put(grammarAccess.getMainStepNumberAccess().getGroup_1(), "rule__MainStepNumber__Group_1__0");
			builder.put(grammarAccess.getExtensionStepNumberAccess().getGroup(), "rule__ExtensionStepNumber__Group__0");
			builder.put(grammarAccess.getExtensionStepNumberAccess().getGroup_2(), "rule__ExtensionStepNumber__Group_2__0");
			builder.put(grammarAccess.getEnvironmentExceptionAccess().getGroup(), "rule__EnvironmentException__Group__0");
			builder.put(grammarAccess.getNetworkExceptionAccess().getGroup(), "rule__NetworkException__Group__0");
			builder.put(grammarAccess.getHardwareExceptionAccess().getGroup(), "rule__HardwareException__Group__0");
			builder.put(grammarAccess.getSoftwareExceptionAccess().getGroup(), "rule__SoftwareException__Group__0");
			builder.put(grammarAccess.getContextExceptionMappingAccess().getGroup(), "rule__ContextExceptionMapping__Group__0");
			builder.put(grammarAccess.getHumanActorAccess().getGroup(), "rule__HumanActor__Group__0");
			builder.put(grammarAccess.getSoftwareActorAccess().getGroup(), "rule__SoftwareActor__Group__0");
			builder.put(grammarAccess.getDeviceActorAccess().getGroup(), "rule__DeviceActor__Group__0");
			builder.put(grammarAccess.getPhysicalEntityActorAccess().getGroup(), "rule__PhysicalEntityActor__Group__0");
			builder.put(grammarAccess.getKeywordStandardModeAccess().getGroup(), "rule__KeywordStandardMode__Group__0");
			builder.put(grammarAccess.getKeywordExceptionalUseCaseAccess().getGroup(), "rule__KeywordExceptionalUseCase__Group__0");
			builder.put(grammarAccess.getKeywordHandlerUseCaseAccess().getGroup(), "rule__KeywordHandlerUseCase__Group__0");
			builder.put(grammarAccess.getKeywordHandlerClassAccess().getGroup(), "rule__KeywordHandlerClass__Group__0");
			builder.put(grammarAccess.getKeywordContextExceptionAccess().getGroup(), "rule__KeywordContextException__Group__0");
			builder.put(grammarAccess.getKeywordMainSuccessScenarioAccess().getGroup(), "rule__KeywordMainSuccessScenario__Group__0");
			builder.put(grammarAccess.getKeywordStepExceptionalBlockAccess().getGroup(), "rule__KeywordStepExceptionalBlock__Group__0");
			builder.put(grammarAccess.getKeywordSceneExceptionBlockAccess().getGroup(), "rule__KeywordSceneExceptionBlock__Group__0");
			builder.put(grammarAccess.getKeywordChildListBeginsAccess().getGroup(), "rule__KeywordChildListBegins__Group__0");
			builder.put(grammarAccess.getKeywordChildListEndsAccess().getGroup(), "rule__KeywordChildListEnds__Group__0");
			builder.put(grammarAccess.getKeywordPrimaryActorAccess().getGroup(), "rule__KeywordPrimaryActor__Group__0");
			builder.put(grammarAccess.getKeywordSecondaryActorAccess().getGroup(), "rule__KeywordSecondaryActor__Group__0");
			builder.put(grammarAccess.getKeywordFacilitatorActorAccess().getGroup(), "rule__KeywordFacilitatorActor__Group__0");
			builder.put(grammarAccess.getKeywordOutcomeEndsAccess().getGroup(), "rule__KeywordOutcomeEnds__Group__0");
			builder.put(grammarAccess.getKeywordOutcomeContAccess().getGroup(), "rule__KeywordOutcomeCont__Group__0");
			builder.put(grammarAccess.getIoTUseCaseModelAccess().getStandardModeAssignment_0_4_0(), "rule__IoTUseCaseModel__StandardModeAssignment_0_4_0");
			builder.put(grammarAccess.getIoTUseCaseModelAccess().getUseCasesAssignment_1(), "rule__IoTUseCaseModel__UseCasesAssignment_1");
			builder.put(grammarAccess.getUseCaseAccess().getMainAssignment_3(), "rule__UseCase__MainAssignment_3");
			builder.put(grammarAccess.getUseCaseAccess().getExtensionsAssignment_4_2(), "rule__UseCase__ExtensionsAssignment_4_2");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getNameAssignment_2(), "rule__ExceptionalUseCase__NameAssignment_2");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getScopeAssignment_3_0_2(), "rule__ExceptionalUseCase__ScopeAssignment_3_0_2");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getIntentAssignment_3_1_2(), "rule__ExceptionalUseCase__IntentAssignment_3_1_2");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getLevelAssignment_3_2_2(), "rule__ExceptionalUseCase__LevelAssignment_3_2_2");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getMultiplicityAssignment_3_3_2(), "rule__ExceptionalUseCase__MultiplicityAssignment_3_3_2");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getPreconditionAssignment_3_4_2(), "rule__ExceptionalUseCase__PreconditionAssignment_3_4_2");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getPostconditionAssignment_3_5_2(), "rule__ExceptionalUseCase__PostconditionAssignment_3_5_2");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getPrimaryActorAssignment_3_6_2_1(), "rule__ExceptionalUseCase__PrimaryActorAssignment_3_6_2_1");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getSecondaryActorsAssignment_3_7_2_1_0(), "rule__ExceptionalUseCase__SecondaryActorsAssignment_3_7_2_1_0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getSecondaryActorsAssignment_3_7_2_1_1_1(), "rule__ExceptionalUseCase__SecondaryActorsAssignment_3_7_2_1_1_1");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getFacilitatorActorsAssignment_3_8_2_1_0(), "rule__ExceptionalUseCase__FacilitatorActorsAssignment_3_8_2_1_0");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getFacilitatorActorsAssignment_3_8_2_1_1_1(), "rule__ExceptionalUseCase__FacilitatorActorsAssignment_3_8_2_1_1_1");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getNameAssignment_2(), "rule__HandlerUseCase__NameAssignment_2");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getScopeAssignment_3_0_2(), "rule__HandlerUseCase__ScopeAssignment_3_0_2");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getIntentAssignment_3_1_2(), "rule__HandlerUseCase__IntentAssignment_3_1_2");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getLevelAssignment_3_2_2(), "rule__HandlerUseCase__LevelAssignment_3_2_2");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getMultiplicityAssignment_3_3_2(), "rule__HandlerUseCase__MultiplicityAssignment_3_3_2");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getPreconditionAssignment_3_4_2(), "rule__HandlerUseCase__PreconditionAssignment_3_4_2");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getPostconditionAssignment_3_5_2(), "rule__HandlerUseCase__PostconditionAssignment_3_5_2");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getPrimaryActorAssignment_3_6_2_1(), "rule__HandlerUseCase__PrimaryActorAssignment_3_6_2_1");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getSecondaryActorsAssignment_3_7_2_1_0(), "rule__HandlerUseCase__SecondaryActorsAssignment_3_7_2_1_0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getSecondaryActorsAssignment_3_7_2_1_1_1(), "rule__HandlerUseCase__SecondaryActorsAssignment_3_7_2_1_1_1");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getFacilitatorActorsAssignment_3_8_2_1_0(), "rule__HandlerUseCase__FacilitatorActorsAssignment_3_8_2_1_0");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getFacilitatorActorsAssignment_3_8_2_1_1_1(), "rule__HandlerUseCase__FacilitatorActorsAssignment_3_8_2_1_1_1");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getHandlerClassAssignment_3_9_2_1(), "rule__HandlerUseCase__HandlerClassAssignment_3_9_2_1");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getContextExceptionsAssignment_3_10_2(), "rule__HandlerUseCase__ContextExceptionsAssignment_3_10_2");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getContextExceptionsAssignment_3_10_3_1(), "rule__HandlerUseCase__ContextExceptionsAssignment_3_10_3_1");
			builder.put(grammarAccess.getMainScenarioAccess().getStepsAssignment_0(), "rule__MainScenario__StepsAssignment_0");
			builder.put(grammarAccess.getMainScenarioAccess().getOutcomeAssignment_1(), "rule__MainScenario__OutcomeAssignment_1");
			builder.put(grammarAccess.getExtensionsAccess().getBlocksAssignment(), "rule__Extensions__BlocksAssignment");
			builder.put(grammarAccess.getAlternateBlockAccess().getRefStepAssignment_2_0(), "rule__AlternateBlock__RefStepAssignment_2_0");
			builder.put(grammarAccess.getAlternateBlockAccess().getHasRangedRefAssignment_2_1_0(), "rule__AlternateBlock__HasRangedRefAssignment_2_1_0");
			builder.put(grammarAccess.getAlternateBlockAccess().getRefStepAssignment_2_1_1(), "rule__AlternateBlock__RefStepAssignment_2_1_1");
			builder.put(grammarAccess.getAlternateBlockAccess().getEndRefStepAssignment_2_1_3(), "rule__AlternateBlock__EndRefStepAssignment_2_1_3");
			builder.put(grammarAccess.getAlternateBlockAccess().getStepsAssignment_4(), "rule__AlternateBlock__StepsAssignment_4");
			builder.put(grammarAccess.getAlternateBlockAccess().getOutcomeAssignment_5_0(), "rule__AlternateBlock__OutcomeAssignment_5_0");
			builder.put(grammarAccess.getAlternateBlockAccess().getBlocksAssignment_5_1_2(), "rule__AlternateBlock__BlocksAssignment_5_1_2");
			builder.put(grammarAccess.getExceptionalBlockAccess().getRefStepAssignment_2_0(), "rule__ExceptionalBlock__RefStepAssignment_2_0");
			builder.put(grammarAccess.getExceptionalBlockAccess().getHasRangedRefAssignment_2_1_0(), "rule__ExceptionalBlock__HasRangedRefAssignment_2_1_0");
			builder.put(grammarAccess.getExceptionalBlockAccess().getRefStepAssignment_2_1_1(), "rule__ExceptionalBlock__RefStepAssignment_2_1_1");
			builder.put(grammarAccess.getExceptionalBlockAccess().getEndRefStepAssignment_2_1_3(), "rule__ExceptionalBlock__EndRefStepAssignment_2_1_3");
			builder.put(grammarAccess.getExceptionalBlockAccess().getStepsAssignment_4(), "rule__ExceptionalBlock__StepsAssignment_4");
			builder.put(grammarAccess.getExceptionalBlockAccess().getOutcomeAssignment_5_0(), "rule__ExceptionalBlock__OutcomeAssignment_5_0");
			builder.put(grammarAccess.getExceptionalBlockAccess().getBlocksAssignment_5_1_2(), "rule__ExceptionalBlock__BlocksAssignment_5_1_2");
			builder.put(grammarAccess.getOutcomeEndsAccess().getTypeAssignment_2(), "rule__OutcomeEnds__TypeAssignment_2");
			builder.put(grammarAccess.getOutcomeContinuesAccess().getStepAssignment_2(), "rule__OutcomeContinues__StepAssignment_2");
			builder.put(grammarAccess.getInteractionStepAccess().getStepNumberAssignment_0(), "rule__InteractionStep__StepNumberAssignment_0");
			builder.put(grammarAccess.getInteractionStepAccess().getExceptionAssignment_2(), "rule__InteractionStep__ExceptionAssignment_2");
			builder.put(grammarAccess.getInteractionStepAccess().getDescriptionAssignment_3_0(), "rule__InteractionStep__DescriptionAssignment_3_0");
			builder.put(grammarAccess.getInteractionStepAccess().getIgnoreDescriptionAssignment_3_1(), "rule__InteractionStep__IgnoreDescriptionAssignment_3_1");
			builder.put(grammarAccess.getInvocationStepAccess().getStepNumberAssignment_0(), "rule__InvocationStep__StepNumberAssignment_0");
			builder.put(grammarAccess.getInvocationStepAccess().getInvokedUseCaseAssignment_3(), "rule__InvocationStep__InvokedUseCaseAssignment_3");
			builder.put(grammarAccess.getInvocationStepAccess().getDescriptionAssignment_5_0(), "rule__InvocationStep__DescriptionAssignment_5_0");
			builder.put(grammarAccess.getInvocationStepAccess().getIgnoreDescriptionAssignment_5_1(), "rule__InvocationStep__IgnoreDescriptionAssignment_5_1");
			builder.put(grammarAccess.getConditionControlStepAccess().getDescriptionAssignment_0(), "rule__ConditionControlStep__DescriptionAssignment_0");
			builder.put(grammarAccess.getConditionControlStepAccess().getIgnoreDescriptionAssignment_1(), "rule__ConditionControlStep__IgnoreDescriptionAssignment_1");
			builder.put(grammarAccess.getEnvironmentExceptionAccess().getNameAssignment_3(), "rule__EnvironmentException__NameAssignment_3");
			builder.put(grammarAccess.getNetworkExceptionAccess().getNameAssignment_3(), "rule__NetworkException__NameAssignment_3");
			builder.put(grammarAccess.getHardwareExceptionAccess().getNameAssignment_3(), "rule__HardwareException__NameAssignment_3");
			builder.put(grammarAccess.getSoftwareExceptionAccess().getNameAssignment_3(), "rule__SoftwareException__NameAssignment_3");
			builder.put(grammarAccess.getContextExceptionMappingAccess().getContextAssignment_0(), "rule__ContextExceptionMapping__ContextAssignment_0");
			builder.put(grammarAccess.getContextExceptionMappingAccess().getExceptionAssignment_4(), "rule__ContextExceptionMapping__ExceptionAssignment_4");
			builder.put(grammarAccess.getPrimaryActorAccess().getNameAssignment_2(), "rule__PrimaryActor__NameAssignment_2");
			builder.put(grammarAccess.getSecondaryActorAccess().getNameAssignment_4(), "rule__SecondaryActor__NameAssignment_4");
			builder.put(grammarAccess.getHumanActorAccess().getNameAssignment_2(), "rule__HumanActor__NameAssignment_2");
			builder.put(grammarAccess.getSoftwareActorAccess().getNameAssignment_2(), "rule__SoftwareActor__NameAssignment_2");
			builder.put(grammarAccess.getDeviceActorAccess().getNameAssignment_2(), "rule__DeviceActor__NameAssignment_2");
			builder.put(grammarAccess.getPhysicalEntityActorAccess().getNameAssignment_2(), "rule__PhysicalEntityActor__NameAssignment_2");
			builder.put(grammarAccess.getExceptionalUseCaseAccess().getUnorderedGroup_3(), "rule__ExceptionalUseCase__UnorderedGroup_3");
			builder.put(grammarAccess.getHandlerUseCaseAccess().getUnorderedGroup_3(), "rule__HandlerUseCase__UnorderedGroup_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private Ucm4iotGrammarAccess grammarAccess;

	@Override
	protected InternalUcm4iotParser createParser() {
		InternalUcm4iotParser result = new InternalUcm4iotParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public Ucm4iotGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Ucm4iotGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
