/*
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class Ucm4iotProposalProvider extends AbstractUcm4iotProposalProvider {
}
