/*
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ui.tests;

import com.google.inject.Injector;
import mde.iot.ucm4iot.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class Ucm4iotUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("mde.iot.ucm4iot.Ucm4iot");
	}

}
