/*
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.parser.antlr;

import com.google.inject.Inject;
import mde.iot.ucm4iot.parser.antlr.internal.InternalUcm4iotParser;
import mde.iot.ucm4iot.services.Ucm4iotGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Ucm4iotParser extends AbstractAntlrParser {

	@Inject
	private Ucm4iotGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUcm4iotParser createParser(XtextTokenStream stream) {
		return new InternalUcm4iotParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "IoTUseCaseModel";
	}

	public Ucm4iotGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Ucm4iotGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
