/*
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Ucm4iotAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("mde/iot/ucm4iot/parser/antlr/internal/InternalUcm4iot.tokens");
	}
}
