/*
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Ucm4iotStandaloneSetup extends Ucm4iotStandaloneSetupGenerated {

	public static void doSetup() {
		new Ucm4iotStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
