/*
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot;

import org.eclipse.xtext.naming.IQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Ucm4iotRuntimeModule extends AbstractUcm4iotRuntimeModule {
	@Override
    public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
        return Ucm4iotQualifiedNameProvider.class;
    }
}
