/*
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Ucm4iotUiModule extends AbstractUcm4iotUiModule {

	public Ucm4iotUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
