/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot.impl;

import mde.iot.ucm4iot.ucm4iot.InvocationStep;
import mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage;
import mde.iot.ucm4iot.ucm4iot.UseCase;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Invocation Step</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.impl.InvocationStepImpl#getStepNumber <em>Step Number</em>}</li>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.impl.InvocationStepImpl#getInvokedUseCase <em>Invoked Use Case</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InvocationStepImpl extends StepImpl implements InvocationStep
{
  /**
   * The default value of the '{@link #getStepNumber() <em>Step Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStepNumber()
   * @generated
   * @ordered
   */
  protected static final String STEP_NUMBER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getStepNumber() <em>Step Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStepNumber()
   * @generated
   * @ordered
   */
  protected String stepNumber = STEP_NUMBER_EDEFAULT;

  /**
   * The cached value of the '{@link #getInvokedUseCase() <em>Invoked Use Case</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInvokedUseCase()
   * @generated
   * @ordered
   */
  protected UseCase invokedUseCase;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InvocationStepImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Ucm4iotPackage.Literals.INVOCATION_STEP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getStepNumber()
  {
    return stepNumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStepNumber(String newStepNumber)
  {
    String oldStepNumber = stepNumber;
    stepNumber = newStepNumber;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Ucm4iotPackage.INVOCATION_STEP__STEP_NUMBER, oldStepNumber, stepNumber));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UseCase getInvokedUseCase()
  {
    if (invokedUseCase != null && invokedUseCase.eIsProxy())
    {
      InternalEObject oldInvokedUseCase = (InternalEObject)invokedUseCase;
      invokedUseCase = (UseCase)eResolveProxy(oldInvokedUseCase);
      if (invokedUseCase != oldInvokedUseCase)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, Ucm4iotPackage.INVOCATION_STEP__INVOKED_USE_CASE, oldInvokedUseCase, invokedUseCase));
      }
    }
    return invokedUseCase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UseCase basicGetInvokedUseCase()
  {
    return invokedUseCase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInvokedUseCase(UseCase newInvokedUseCase)
  {
    UseCase oldInvokedUseCase = invokedUseCase;
    invokedUseCase = newInvokedUseCase;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Ucm4iotPackage.INVOCATION_STEP__INVOKED_USE_CASE, oldInvokedUseCase, invokedUseCase));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Ucm4iotPackage.INVOCATION_STEP__STEP_NUMBER:
        return getStepNumber();
      case Ucm4iotPackage.INVOCATION_STEP__INVOKED_USE_CASE:
        if (resolve) return getInvokedUseCase();
        return basicGetInvokedUseCase();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Ucm4iotPackage.INVOCATION_STEP__STEP_NUMBER:
        setStepNumber((String)newValue);
        return;
      case Ucm4iotPackage.INVOCATION_STEP__INVOKED_USE_CASE:
        setInvokedUseCase((UseCase)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Ucm4iotPackage.INVOCATION_STEP__STEP_NUMBER:
        setStepNumber(STEP_NUMBER_EDEFAULT);
        return;
      case Ucm4iotPackage.INVOCATION_STEP__INVOKED_USE_CASE:
        setInvokedUseCase((UseCase)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Ucm4iotPackage.INVOCATION_STEP__STEP_NUMBER:
        return STEP_NUMBER_EDEFAULT == null ? stepNumber != null : !STEP_NUMBER_EDEFAULT.equals(stepNumber);
      case Ucm4iotPackage.INVOCATION_STEP__INVOKED_USE_CASE:
        return invokedUseCase != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (stepNumber: ");
    result.append(stepNumber);
    result.append(')');
    return result.toString();
  }

} //InvocationStepImpl
