/*
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractUcm4iotValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage.eINSTANCE);
		return result;
	}
}
