/*
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import mde.iot.ucm4iot.Ucm4iotRuntimeModule;
import mde.iot.ucm4iot.Ucm4iotStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Ucm4iotIdeSetup extends Ucm4iotStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Ucm4iotRuntimeModule(), new Ucm4iotIdeModule()));
	}
	
}
