/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition Control Step</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getConditionControlStep()
 * @model
 * @generated
 */
public interface ConditionControlStep extends Step
{
} // ConditionControlStep
