/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context Exception Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.ContextExceptionMapping#getContext <em>Context</em>}</li>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.ContextExceptionMapping#getException <em>Exception</em>}</li>
 * </ul>
 *
 * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getContextExceptionMapping()
 * @model
 * @generated
 */
public interface ContextExceptionMapping extends EObject
{
  /**
   * Returns the value of the '<em><b>Context</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context</em>' reference.
   * @see #setContext(UseCase)
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getContextExceptionMapping_Context()
   * @model
   * @generated
   */
  UseCase getContext();

  /**
   * Sets the value of the '{@link mde.iot.ucm4iot.ucm4iot.ContextExceptionMapping#getContext <em>Context</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context</em>' reference.
   * @see #getContext()
   * @generated
   */
  void setContext(UseCase value);

  /**
   * Returns the value of the '<em><b>Exception</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exception</em>' reference.
   * @see #setException(mde.iot.ucm4iot.ucm4iot.Exception)
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getContextExceptionMapping_Exception()
   * @model
   * @generated
   */
  mde.iot.ucm4iot.ucm4iot.Exception getException();

  /**
   * Sets the value of the '{@link mde.iot.ucm4iot.ucm4iot.ContextExceptionMapping#getException <em>Exception</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exception</em>' reference.
   * @see #getException()
   * @generated
   */
  void setException(mde.iot.ucm4iot.ucm4iot.Exception value);

} // ContextExceptionMapping
