/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Environment Exception</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getEnvironmentException()
 * @model
 * @generated
 */
public interface EnvironmentException extends mde.iot.ucm4iot.ucm4iot.Exception
{
} // EnvironmentException
