/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extension Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.ExtensionBlock#getRefStep <em>Ref Step</em>}</li>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.ExtensionBlock#isHasRangedRef <em>Has Ranged Ref</em>}</li>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.ExtensionBlock#getEndRefStep <em>End Ref Step</em>}</li>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.ExtensionBlock#getSteps <em>Steps</em>}</li>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.ExtensionBlock#getOutcome <em>Outcome</em>}</li>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.ExtensionBlock#getBlocks <em>Blocks</em>}</li>
 * </ul>
 *
 * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getExtensionBlock()
 * @model
 * @generated
 */
public interface ExtensionBlock extends EObject
{
  /**
   * Returns the value of the '<em><b>Ref Step</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref Step</em>' reference.
   * @see #setRefStep(Step)
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getExtensionBlock_RefStep()
   * @model
   * @generated
   */
  Step getRefStep();

  /**
   * Sets the value of the '{@link mde.iot.ucm4iot.ucm4iot.ExtensionBlock#getRefStep <em>Ref Step</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref Step</em>' reference.
   * @see #getRefStep()
   * @generated
   */
  void setRefStep(Step value);

  /**
   * Returns the value of the '<em><b>Has Ranged Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Has Ranged Ref</em>' attribute.
   * @see #setHasRangedRef(boolean)
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getExtensionBlock_HasRangedRef()
   * @model
   * @generated
   */
  boolean isHasRangedRef();

  /**
   * Sets the value of the '{@link mde.iot.ucm4iot.ucm4iot.ExtensionBlock#isHasRangedRef <em>Has Ranged Ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Has Ranged Ref</em>' attribute.
   * @see #isHasRangedRef()
   * @generated
   */
  void setHasRangedRef(boolean value);

  /**
   * Returns the value of the '<em><b>End Ref Step</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Ref Step</em>' reference.
   * @see #setEndRefStep(Step)
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getExtensionBlock_EndRefStep()
   * @model
   * @generated
   */
  Step getEndRefStep();

  /**
   * Sets the value of the '{@link mde.iot.ucm4iot.ucm4iot.ExtensionBlock#getEndRefStep <em>End Ref Step</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Ref Step</em>' reference.
   * @see #getEndRefStep()
   * @generated
   */
  void setEndRefStep(Step value);

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference list.
   * The list contents are of type {@link mde.iot.ucm4iot.ucm4iot.Step}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference list.
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getExtensionBlock_Steps()
   * @model containment="true"
   * @generated
   */
  EList<Step> getSteps();

  /**
   * Returns the value of the '<em><b>Outcome</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Outcome</em>' containment reference.
   * @see #setOutcome(Outcome)
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getExtensionBlock_Outcome()
   * @model containment="true"
   * @generated
   */
  Outcome getOutcome();

  /**
   * Sets the value of the '{@link mde.iot.ucm4iot.ucm4iot.ExtensionBlock#getOutcome <em>Outcome</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Outcome</em>' containment reference.
   * @see #getOutcome()
   * @generated
   */
  void setOutcome(Outcome value);

  /**
   * Returns the value of the '<em><b>Blocks</b></em>' containment reference list.
   * The list contents are of type {@link mde.iot.ucm4iot.ucm4iot.ExtensionBlock}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Blocks</em>' containment reference list.
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getExtensionBlock_Blocks()
   * @model containment="true"
   * @generated
   */
  EList<ExtensionBlock> getBlocks();

} // ExtensionBlock
