/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extensions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.Extensions#getBlocks <em>Blocks</em>}</li>
 * </ul>
 *
 * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getExtensions()
 * @model
 * @generated
 */
public interface Extensions extends EObject
{
  /**
   * Returns the value of the '<em><b>Blocks</b></em>' containment reference list.
   * The list contents are of type {@link mde.iot.ucm4iot.ucm4iot.ExtensionBlock}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Blocks</em>' containment reference list.
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getExtensions_Blocks()
   * @model containment="true"
   * @generated
   */
  EList<ExtensionBlock> getBlocks();

} // Extensions
