/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hardware Exception</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getHardwareException()
 * @model
 * @generated
 */
public interface HardwareException extends mde.iot.ucm4iot.ucm4iot.Exception
{
} // HardwareException
