/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Invocation Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.InvocationStep#getStepNumber <em>Step Number</em>}</li>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.InvocationStep#getInvokedUseCase <em>Invoked Use Case</em>}</li>
 * </ul>
 *
 * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getInvocationStep()
 * @model
 * @generated
 */
public interface InvocationStep extends Step
{
  /**
   * Returns the value of the '<em><b>Step Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Step Number</em>' attribute.
   * @see #setStepNumber(String)
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getInvocationStep_StepNumber()
   * @model
   * @generated
   */
  String getStepNumber();

  /**
   * Sets the value of the '{@link mde.iot.ucm4iot.ucm4iot.InvocationStep#getStepNumber <em>Step Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Step Number</em>' attribute.
   * @see #getStepNumber()
   * @generated
   */
  void setStepNumber(String value);

  /**
   * Returns the value of the '<em><b>Invoked Use Case</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invoked Use Case</em>' reference.
   * @see #setInvokedUseCase(UseCase)
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getInvocationStep_InvokedUseCase()
   * @model
   * @generated
   */
  UseCase getInvokedUseCase();

  /**
   * Sets the value of the '{@link mde.iot.ucm4iot.ucm4iot.InvocationStep#getInvokedUseCase <em>Invoked Use Case</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Invoked Use Case</em>' reference.
   * @see #getInvokedUseCase()
   * @generated
   */
  void setInvokedUseCase(UseCase value);

} // InvocationStep
