/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Io TUse Case Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.IoTUseCaseModel#isStandardMode <em>Standard Mode</em>}</li>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.IoTUseCaseModel#getUseCases <em>Use Cases</em>}</li>
 * </ul>
 *
 * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getIoTUseCaseModel()
 * @model
 * @generated
 */
public interface IoTUseCaseModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Standard Mode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Standard Mode</em>' attribute.
   * @see #setStandardMode(boolean)
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getIoTUseCaseModel_StandardMode()
   * @model
   * @generated
   */
  boolean isStandardMode();

  /**
   * Sets the value of the '{@link mde.iot.ucm4iot.ucm4iot.IoTUseCaseModel#isStandardMode <em>Standard Mode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Standard Mode</em>' attribute.
   * @see #isStandardMode()
   * @generated
   */
  void setStandardMode(boolean value);

  /**
   * Returns the value of the '<em><b>Use Cases</b></em>' containment reference list.
   * The list contents are of type {@link mde.iot.ucm4iot.ucm4iot.UseCase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Use Cases</em>' containment reference list.
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getIoTUseCaseModel_UseCases()
   * @model containment="true"
   * @generated
   */
  EList<UseCase> getUseCases();

} // IoTUseCaseModel
