/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Level</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getLevel()
 * @model
 * @generated
 */
public enum Level implements Enumerator
{
  /**
   * The '<em><b>SUMMARY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SUMMARY_VALUE
   * @generated
   * @ordered
   */
  SUMMARY(0, "SUMMARY", "SUMMARY"),

  /**
   * The '<em><b>USER GOAL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #USER_GOAL_VALUE
   * @generated
   * @ordered
   */
  USER_GOAL(1, "USER_GOAL", "USER_GOAL"),

  /**
   * The '<em><b>SUBFUNCTION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SUBFUNCTION_VALUE
   * @generated
   * @ordered
   */
  SUBFUNCTION(2, "SUBFUNCTION", "SUB_FUNCTION");

  /**
   * The '<em><b>SUMMARY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SUMMARY
   * @model
   * @generated
   * @ordered
   */
  public static final int SUMMARY_VALUE = 0;

  /**
   * The '<em><b>USER GOAL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #USER_GOAL
   * @model
   * @generated
   * @ordered
   */
  public static final int USER_GOAL_VALUE = 1;

  /**
   * The '<em><b>SUBFUNCTION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SUBFUNCTION
   * @model literal="SUB_FUNCTION"
   * @generated
   * @ordered
   */
  public static final int SUBFUNCTION_VALUE = 2;

  /**
   * An array of all the '<em><b>Level</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Level[] VALUES_ARRAY =
    new Level[]
    {
      SUMMARY,
      USER_GOAL,
      SUBFUNCTION,
    };

  /**
   * A public read-only list of all the '<em><b>Level</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Level> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Level</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Level get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Level result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Level</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Level getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Level result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Level</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Level get(int value)
  {
    switch (value)
    {
      case SUMMARY_VALUE: return SUMMARY;
      case USER_GOAL_VALUE: return USER_GOAL;
      case SUBFUNCTION_VALUE: return SUBFUNCTION;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Level(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Level
