/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Outcome</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getOutcome()
 * @model
 * @generated
 */
public interface Outcome extends EObject
{
} // Outcome
