/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Outcome Ends</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.OutcomeEnds#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getOutcomeEnds()
 * @model
 * @generated
 */
public interface OutcomeEnds extends Outcome
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link mde.iot.ucm4iot.ucm4iot.OutcomeEndings}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see mde.iot.ucm4iot.ucm4iot.OutcomeEndings
   * @see #setType(OutcomeEndings)
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getOutcomeEnds_Type()
   * @model
   * @generated
   */
  OutcomeEndings getType();

  /**
   * Sets the value of the '{@link mde.iot.ucm4iot.ucm4iot.OutcomeEnds#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see mde.iot.ucm4iot.ucm4iot.OutcomeEndings
   * @see #getType()
   * @generated
   */
  void setType(OutcomeEndings value);

} // OutcomeEnds
