/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Outcome Continues</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.OutcomeContinues#getStep <em>Step</em>}</li>
 * </ul>
 *
 * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getOutcomeContinues()
 * @model
 * @generated
 */
public interface OutcomeContinues extends Outcome
{
  /**
   * Returns the value of the '<em><b>Step</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Step</em>' reference.
   * @see #setStep(Step)
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getOutcomeContinues_Step()
   * @model
   * @generated
   */
  Step getStep();

  /**
   * Sets the value of the '{@link mde.iot.ucm4iot.ucm4iot.OutcomeContinues#getStep <em>Step</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Step</em>' reference.
   * @see #getStep()
   * @generated
   */
  void setStep(Step value);

} // OutcomeContinues
