/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Software Actor</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getSoftwareActor()
 * @model
 * @generated
 */
public interface SoftwareActor extends PrimaryActor, SecondaryActor
{
} // SoftwareActor
