/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.Step#getDescription <em>Description</em>}</li>
 *   <li>{@link mde.iot.ucm4iot.ucm4iot.Step#isIgnoreDescription <em>Ignore Description</em>}</li>
 * </ul>
 *
 * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getStep()
 * @model
 * @generated
 */
public interface Step extends EObject
{
  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getStep_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link mde.iot.ucm4iot.ucm4iot.Step#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Ignore Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ignore Description</em>' attribute.
   * @see #setIgnoreDescription(boolean)
   * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage#getStep_IgnoreDescription()
   * @model
   * @generated
   */
  boolean isIgnoreDescription();

  /**
   * Sets the value of the '{@link mde.iot.ucm4iot.ucm4iot.Step#isIgnoreDescription <em>Ignore Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ignore Description</em>' attribute.
   * @see #isIgnoreDescription()
   * @generated
   */
  void setIgnoreDescription(boolean value);

} // Step
