/**
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.ucm4iot;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see mde.iot.ucm4iot.ucm4iot.Ucm4iotPackage
 * @generated
 */
public interface Ucm4iotFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Ucm4iotFactory eINSTANCE = mde.iot.ucm4iot.ucm4iot.impl.Ucm4iotFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Io TUse Case Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Io TUse Case Model</em>'.
   * @generated
   */
  IoTUseCaseModel createIoTUseCaseModel();

  /**
   * Returns a new object of class '<em>Use Case</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Use Case</em>'.
   * @generated
   */
  UseCase createUseCase();

  /**
   * Returns a new object of class '<em>Exceptional Use Case</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exceptional Use Case</em>'.
   * @generated
   */
  ExceptionalUseCase createExceptionalUseCase();

  /**
   * Returns a new object of class '<em>Handler Use Case</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Handler Use Case</em>'.
   * @generated
   */
  HandlerUseCase createHandlerUseCase();

  /**
   * Returns a new object of class '<em>Main Scenario</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Main Scenario</em>'.
   * @generated
   */
  MainScenario createMainScenario();

  /**
   * Returns a new object of class '<em>Extensions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Extensions</em>'.
   * @generated
   */
  Extensions createExtensions();

  /**
   * Returns a new object of class '<em>Extension Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Extension Block</em>'.
   * @generated
   */
  ExtensionBlock createExtensionBlock();

  /**
   * Returns a new object of class '<em>Alternate Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Alternate Block</em>'.
   * @generated
   */
  AlternateBlock createAlternateBlock();

  /**
   * Returns a new object of class '<em>Exceptional Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exceptional Block</em>'.
   * @generated
   */
  ExceptionalBlock createExceptionalBlock();

  /**
   * Returns a new object of class '<em>Outcome</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Outcome</em>'.
   * @generated
   */
  Outcome createOutcome();

  /**
   * Returns a new object of class '<em>Outcome Ends</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Outcome Ends</em>'.
   * @generated
   */
  OutcomeEnds createOutcomeEnds();

  /**
   * Returns a new object of class '<em>Outcome Continues</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Outcome Continues</em>'.
   * @generated
   */
  OutcomeContinues createOutcomeContinues();

  /**
   * Returns a new object of class '<em>Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Step</em>'.
   * @generated
   */
  Step createStep();

  /**
   * Returns a new object of class '<em>Interaction Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Interaction Step</em>'.
   * @generated
   */
  InteractionStep createInteractionStep();

  /**
   * Returns a new object of class '<em>Invocation Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Invocation Step</em>'.
   * @generated
   */
  InvocationStep createInvocationStep();

  /**
   * Returns a new object of class '<em>Condition Control Step</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition Control Step</em>'.
   * @generated
   */
  ConditionControlStep createConditionControlStep();

  /**
   * Returns a new object of class '<em>Exception</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exception</em>'.
   * @generated
   */
  Exception createException();

  /**
   * Returns a new object of class '<em>Environment Exception</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Environment Exception</em>'.
   * @generated
   */
  EnvironmentException createEnvironmentException();

  /**
   * Returns a new object of class '<em>Network Exception</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Network Exception</em>'.
   * @generated
   */
  NetworkException createNetworkException();

  /**
   * Returns a new object of class '<em>Hardware Exception</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Hardware Exception</em>'.
   * @generated
   */
  HardwareException createHardwareException();

  /**
   * Returns a new object of class '<em>Software Exception</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Software Exception</em>'.
   * @generated
   */
  SoftwareException createSoftwareException();

  /**
   * Returns a new object of class '<em>Context Exception Mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Context Exception Mapping</em>'.
   * @generated
   */
  ContextExceptionMapping createContextExceptionMapping();

  /**
   * Returns a new object of class '<em>Actor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Actor</em>'.
   * @generated
   */
  Actor createActor();

  /**
   * Returns a new object of class '<em>Primary Actor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primary Actor</em>'.
   * @generated
   */
  PrimaryActor createPrimaryActor();

  /**
   * Returns a new object of class '<em>Secondary Actor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Secondary Actor</em>'.
   * @generated
   */
  SecondaryActor createSecondaryActor();

  /**
   * Returns a new object of class '<em>Human Actor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Human Actor</em>'.
   * @generated
   */
  HumanActor createHumanActor();

  /**
   * Returns a new object of class '<em>Software Actor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Software Actor</em>'.
   * @generated
   */
  SoftwareActor createSoftwareActor();

  /**
   * Returns a new object of class '<em>Device Actor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Device Actor</em>'.
   * @generated
   */
  DeviceActor createDeviceActor();

  /**
   * Returns a new object of class '<em>Physical Entity Actor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Physical Entity Actor</em>'.
   * @generated
   */
  PhysicalEntityActor createPhysicalEntityActor();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  Ucm4iotPackage getUcm4iotPackage();

} //Ucm4iotFactory
