/*
 * generated by Xtext 2.25.0
 */
package mde.iot.ucm4iot.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUcm4iotScopeProvider extends DelegatingScopeProvider {
}
